version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_test

    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
