spring.application.name=postgresTest

spring.datasource.url=jdbc:postgresql://localhost:5435/test_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update